"""
dmx.py

Software-timed DMX512 output for a generic "USB-DMX512" interface - the
common sub-GBP30 dongles (AliExpress/Amazon generic, and the genuine
Enttec Open DMX USB they clone) that are just an FTDI (or CH340) USB-
serial chip wired to a MAX485 transceiver, with no onboard microcontroller
of their own. That matters because there's no vendor packet protocol to
speak here (unlike the Enttec DMX USB PRO, which has its own chip and
expects framed packets over serial) - every part of a DMX512 frame has to
be generated by the host over the raw serial line:

  1. Break: line held low for >=92us, marking the start of a new frame.
     pyserial's Serial.send_break() generates this.
  2. Mark-after-break (MAB): line back high for >=12us before data starts -
     covered by the gap between send_break() returning and the following
     write() call.
  3. Start code (0x00 - "standard dimmer data", what RGB/RGBW fixtures
     expect) followed by up to 512 channel bytes, at 250000 baud, 8 data
     bits, 2 stop bits, no parity (DMX512's own framing, distinct from the
     break above).

If this turns out to actually be an Enttec DMX USB PRO (or clone) rather
than an Open-DMX-style dongle, this module is the wrong driver for it -
the PRO expects packets wrapped in its own protocol (0x7E ... 0xE7) and
handles DMX timing itself. Re-check once the interface is in hand
(Device Manager -> Ports, or `python -m tools.test_dmx ports`).

Falls back to printing frames if pyserial isn't installed or no interface
is found/openable - same "safe on a dev laptop, real once wired up"
contract as output/leds.py's LEDStrip.
"""
try:
    import serial
    from serial.tools import list_ports
except ImportError:
    serial = None
    list_ports = None

UNIVERSE_SIZE = 512
DMX_BAUD = 250000
START_CODE = 0x00

# Vendor IDs of the USB-serial chips almost every cheap Open-DMX-style
# dongle is built around - FTDI (genuine Enttec Open DMX USB and most
# clones) and CH340 (some budget clones). Used by find_port() to guess
# which serial port the dongle is on without the user having to look it up.
KNOWN_CHIP_VIDS = {0x0403, 0x1A86}


def find_port():
    """Best-effort guess at which serial port the DMX dongle is on - the
    first port whose USB-serial chip matches KNOWN_CHIP_VIDS. Returns None
    if pyserial isn't installed or nothing matches, so the caller can print
    instructions instead of crashing. Run `python -m tools.test_dmx ports`
    to see every serial port and its vendor ID if auto-detect picks the
    wrong one (e.g. another USB-serial device is also plugged in)."""
    if list_ports is None:
        return None
    for port in list_ports.comports():
        if port.vid in KNOWN_CHIP_VIDS:
            return port.device
    return None


class DMXInterface:
    def __init__(self, port: str = None, universe_size: int = UNIVERSE_SIZE):
        self.universe_size = universe_size
        self._serial = None

        if serial is None:
            print("[DMXInterface] pyserial not installed - printing frames instead of driving real fixtures (pip install pyserial)")
            return

        port = port or find_port()
        if port is None:
            print("[DMXInterface] no USB-DMX interface found (looked for an FTDI/CH340 serial port) - printing frames instead. Pass an explicit port (e.g. 'COM5') if it's plugged in but not auto-detecting.")
            return

        try:
            self._serial = serial.Serial(
                port=port, baudrate=DMX_BAUD,
                bytesize=serial.EIGHTBITS, stopbits=serial.STOPBITS_TWO,
                parity=serial.PARITY_NONE, timeout=1.0,
            )
            # Some RS485 USB-DMX breakouts wire their auto-direction chip's
            # enable pin to RTS rather than driving it themselves - setting
            # this is a no-op on dongles that don't need it, and required on
            # the ones that do, so it's set unconditionally rather than
            # guessed at per-dongle.
            self._serial.rts = True
            print(f"[DMXInterface] opened {port} at {DMX_BAUD} baud")
        except Exception as exc:
            print(f"[DMXInterface] couldn't open {port} ({exc}) - printing frames instead")
            self._serial = None

    def send_channels(self, channels: list) -> None:
        """channels: list of ints (0-255), channel 1 first. Padded/truncated
        to universe_size. Sends one full DMX512 frame (break + MAB + start
        code + data) - call this every refresh, same as LEDStrip.render_pixels."""
        data = bytes(int(max(0, min(255, c))) for c in channels[:self.universe_size])
        data = data + bytes(self.universe_size - len(data))

        if self._serial is None:
            print(f"DMX [{len(data)}ch] first={list(data[:4])}")
            return

        try:
            # 0.001s is far longer than DMX's 92us minimum break, with
            # plenty of margin for a cheap dongle's timing tolerances -
            # still fast enough for a smooth-looking refresh rate.
            self._serial.send_break(0.001)
            self._serial.write(bytes([START_CODE]) + data)
            self._serial.flush()
        except Exception as exc:
            print(f"[DMXInterface] write failed ({exc})")

    def blackout(self) -> None:
        self.send_channels([0] * self.universe_size)
