"""audio_scene_categories.py

AUDIO_SCENE_CATEGORY maps every one of YAMNet's 521 leaf class names (the
`audio_scene` field AudioSensor reports, see src/sensing/audio.py) to one of
AudioSet's 7 top-level ontology categories. Generated once, offline, from
Google's own published AudioSet ontology - not hand-curated and not
re-fetched at runtime - so rules.py can reason about "is this scene
Music-like / background-like / etc." without needing a hardcoded list of
every possible class name it might see (there are 521, e.g. "Reggae",
"Kettle whistle", "Cowbell", ...).

Regenerate with the ontology + YAMNet's own class map:
  ontology.json:          https://raw.githubusercontent.com/audioset/ontology/master/ontology.json
  yamnet_class_map.csv:    https://raw.githubusercontent.com/tensorflow/models/master/research/audioset/yamnet/yamnet_class_map.csv
by walking each leaf's parent_ids up to a top-level root (a node that's
never anyone else's child). ~29 of the 521 leaves are double-homed under
more than one top-level category in AudioSet's DAG (e.g. "Bell" sits under
both "Sounds of things" and "Music") - those were resolved with a fixed
priority order (see the generation script / CLAUDE.md context), not by
re-deriving it from the ontology at runtime.

The 7 top-level categories that appear as values below: "Human sounds",
"Animal", "Music", "Natural sounds", "Sounds of things",
"Source-ambiguous sounds", "Channel, environment and background".
"""

AUDIO_SCENE_CATEGORY = {
    'A capella': 'Music',
    'Accelerating, revving, vroom': 'Sounds of things',
    'Accordion': 'Music',
    'Acoustic guitar': 'Music',
    'Afrobeat': 'Music',
    'Air brake': 'Sounds of things',
    'Air conditioning': 'Sounds of things',
    'Air horn, truck horn': 'Sounds of things',
    'Aircraft': 'Sounds of things',
    'Aircraft engine': 'Sounds of things',
    'Alarm': 'Sounds of things',
    'Alarm clock': 'Sounds of things',
    'Ambient music': 'Music',
    'Ambulance (siren)': 'Sounds of things',
    'Angry music': 'Music',
    'Animal': 'Animal',
    'Applause': 'Human sounds',
    'Arrow': 'Sounds of things',
    'Artillery fire': 'Sounds of things',
    'Babbling': 'Human sounds',
    'Baby cry, infant cry': 'Human sounds',
    'Baby laughter': 'Human sounds',
    'Background music': 'Music',
    'Bagpipes': 'Music',
    'Bang': 'Source-ambiguous sounds',
    'Banjo': 'Music',
    'Bark': 'Animal',
    'Basketball bounce': 'Sounds of things',
    'Bass drum': 'Music',
    'Bass guitar': 'Music',
    'Bathtub (filling or washing)': 'Sounds of things',
    'Beatboxing': 'Music',
    'Bee, wasp, etc.': 'Animal',
    'Beep, bleep': 'Source-ambiguous sounds',
    'Bell': 'Music',
    'Bellow': 'Human sounds',
    'Belly laugh': 'Human sounds',
    'Bicycle': 'Sounds of things',
    'Bicycle bell': 'Music',
    'Bird': 'Animal',
    'Bird flight, flapping wings': 'Animal',
    'Bird vocalization, bird call, bird song': 'Animal',
    'Biting': 'Human sounds',
    'Bleat': 'Animal',
    'Blender': 'Sounds of things',
    'Bluegrass': 'Music',
    'Blues': 'Music',
    'Boat, Water vehicle': 'Sounds of things',
    'Boiling': 'Sounds of things',
    'Boing': 'Source-ambiguous sounds',
    'Boom': 'Sounds of things',
    'Bouncing': 'Source-ambiguous sounds',
    'Bow-wow': 'Animal',
    'Bowed string instrument': 'Music',
    'Brass instrument': 'Music',
    'Breaking': 'Source-ambiguous sounds',
    'Breathing': 'Human sounds',
    'Burping, eructation': 'Human sounds',
    'Burst, pop': 'Sounds of things',
    'Bus': 'Sounds of things',
    'Busy signal': 'Sounds of things',
    'Buzz': 'Animal',
    'Buzzer': 'Sounds of things',
    'Cacophony': 'Channel, environment and background',
    'Camera': 'Sounds of things',
    'Canidae, dogs, wolves': 'Animal',
    'Cap gun': 'Sounds of things',
    'Car': 'Sounds of things',
    'Car alarm': 'Sounds of things',
    'Car passing by': 'Sounds of things',
    'Carnatic music': 'Music',
    'Cash register': 'Sounds of things',
    'Cat': 'Animal',
    'Caterwaul': 'Animal',
    'Cattle, bovinae': 'Animal',
    'Caw': 'Animal',
    'Cello': 'Music',
    'Chainsaw': 'Sounds of things',
    'Change ringing (campanology)': 'Music',
    'Chant': 'Music',
    'Chatter': 'Human sounds',
    'Cheering': 'Human sounds',
    'Chewing, mastication': 'Human sounds',
    'Chicken, rooster': 'Animal',
    'Child singing': 'Human sounds',
    'Child speech, kid speaking': 'Human sounds',
    'Children playing': 'Human sounds',
    'Children shouting': 'Human sounds',
    'Chime': 'Music',
    'Chink, clink': 'Sounds of things',
    'Chirp tone': 'Source-ambiguous sounds',
    'Chirp, tweet': 'Animal',
    'Choir': 'Music',
    'Chop': 'Sounds of things',
    'Chopping (food)': 'Sounds of things',
    'Chorus effect': 'Sounds of things',
    'Christian music': 'Music',
    'Christmas music': 'Music',
    'Chuckle, chortle': 'Human sounds',
    'Church bell': 'Music',
    'Civil defense siren': 'Sounds of things',
    'Clang': 'Source-ambiguous sounds',
    'Clapping': 'Human sounds',
    'Clarinet': 'Music',
    'Classical music': 'Music',
    'Clatter': 'Source-ambiguous sounds',
    'Clickety-clack': 'Source-ambiguous sounds',
    'Clicking': 'Source-ambiguous sounds',
    'Clip-clop': 'Animal',
    'Clock': 'Sounds of things',
    'Cluck': 'Animal',
    'Coin (dropping)': 'Sounds of things',
    'Computer keyboard': 'Sounds of things',
    'Conversation': 'Human sounds',
    'Coo': 'Animal',
    'Cough': 'Human sounds',
    'Country': 'Music',
    'Cowbell': 'Music',
    'Crack': 'Sounds of things',
    'Crackle': 'Natural sounds',
    'Creak': 'Source-ambiguous sounds',
    'Cricket': 'Animal',
    'Croak': 'Animal',
    'Crow': 'Animal',
    'Crowd': 'Human sounds',
    'Crowing, cock-a-doodle-doo': 'Animal',
    'Crumpling, crinkling': 'Source-ambiguous sounds',
    'Crunch': 'Source-ambiguous sounds',
    'Crushing': 'Source-ambiguous sounds',
    'Crying, sobbing': 'Human sounds',
    'Cupboard open or close': 'Sounds of things',
    'Cutlery, silverware': 'Sounds of things',
    'Cymbal': 'Music',
    'Dance music': 'Music',
    "Dental drill, dentist's drill": 'Sounds of things',
    'Dial tone': 'Sounds of things',
    'Didgeridoo': 'Music',
    'Ding': 'Source-ambiguous sounds',
    'Ding-dong': 'Sounds of things',
    'Disco': 'Music',
    'Dishes, pots, and pans': 'Sounds of things',
    'Distortion': 'Channel, environment and background',
    'Dog': 'Animal',
    'Domestic animals, pets': 'Animal',
    'Door': 'Sounds of things',
    'Doorbell': 'Sounds of things',
    'Double bass': 'Music',
    'Drawer open or close': 'Sounds of things',
    'Drill': 'Sounds of things',
    'Drip': 'Sounds of things',
    'Drum': 'Music',
    'Drum and bass': 'Music',
    'Drum kit': 'Music',
    'Drum machine': 'Music',
    'Drum roll': 'Music',
    'Dubstep': 'Music',
    'Duck': 'Animal',
    'Echo': 'Channel, environment and background',
    'Effects unit': 'Sounds of things',
    'Electric guitar': 'Music',
    'Electric piano': 'Music',
    'Electric shaver, electric razor': 'Sounds of things',
    'Electric toothbrush': 'Sounds of things',
    'Electronic dance music': 'Music',
    'Electronic music': 'Music',
    'Electronic organ': 'Music',
    'Electronic tuner': 'Sounds of things',
    'Electronica': 'Music',
    'Emergency vehicle': 'Sounds of things',
    'Engine': 'Sounds of things',
    'Engine knocking': 'Sounds of things',
    'Engine starting': 'Sounds of things',
    'Environmental noise': 'Channel, environment and background',
    'Eruption': 'Sounds of things',
    'Exciting music': 'Music',
    'Explosion': 'Sounds of things',
    'Fart': 'Human sounds',
    'Field recording': 'Channel, environment and background',
    'Filing (rasp)': 'Sounds of things',
    'Fill (with liquid)': 'Sounds of things',
    'Finger snapping': 'Human sounds',
    'Fire': 'Natural sounds',
    'Fire alarm': 'Sounds of things',
    'Fire engine, fire truck (siren)': 'Sounds of things',
    'Firecracker': 'Sounds of things',
    'Fireworks': 'Sounds of things',
    'Fixed-wing aircraft, airplane': 'Sounds of things',
    'Flamenco': 'Music',
    'Flap': 'Source-ambiguous sounds',
    'Flute': 'Music',
    'Fly, housefly': 'Animal',
    'Foghorn': 'Sounds of things',
    'Folk music': 'Music',
    'Fowl': 'Animal',
    'French horn': 'Music',
    'Frog': 'Animal',
    'Frying (food)': 'Sounds of things',
    'Funk': 'Music',
    'Fusillade': 'Sounds of things',
    'Gargling': 'Human sounds',
    'Gasp': 'Human sounds',
    'Gears': 'Sounds of things',
    'Giggle': 'Human sounds',
    'Glass': 'Sounds of things',
    'Glockenspiel': 'Music',
    'Goat': 'Animal',
    'Gobble': 'Animal',
    'Gong': 'Music',
    'Goose': 'Animal',
    'Gospel music': 'Music',
    'Groan': 'Human sounds',
    'Growling': 'Animal',
    'Grunge': 'Music',
    'Grunt': 'Human sounds',
    'Guitar': 'Music',
    'Gunshot, gunfire': 'Sounds of things',
    'Gurgling': 'Natural sounds',
    'Gush': 'Sounds of things',
    'Hair dryer': 'Sounds of things',
    'Hammer': 'Sounds of things',
    'Hammond organ': 'Music',
    'Hands': 'Human sounds',
    'Happy music': 'Music',
    'Harmonic': 'Source-ambiguous sounds',
    'Harmonica': 'Music',
    'Harp': 'Music',
    'Harpsichord': 'Music',
    'Heart murmur': 'Human sounds',
    'Heart sounds, heartbeat': 'Human sounds',
    'Heavy engine (low frequency)': 'Sounds of things',
    'Heavy metal': 'Music',
    'Helicopter': 'Sounds of things',
    'Hi-hat': 'Music',
    'Hiccup': 'Human sounds',
    'Hip hop music': 'Music',
    'Hiss': 'Animal',
    'Honk': 'Animal',
    'Hoot': 'Animal',
    'Horse': 'Animal',
    'House music': 'Music',
    'Howl': 'Animal',
    'Hubbub, speech noise, speech babble': 'Human sounds',
    'Hum': 'Source-ambiguous sounds',
    'Humming': 'Human sounds',
    'Ice cream truck, ice cream van': 'Sounds of things',
    'Idling': 'Sounds of things',
    'Independent music': 'Music',
    'Insect': 'Animal',
    'Inside, large room or hall': 'Channel, environment and background',
    'Inside, public space': 'Channel, environment and background',
    'Inside, small room': 'Channel, environment and background',
    'Jackhammer': 'Sounds of things',
    'Jazz': 'Music',
    'Jet engine': 'Sounds of things',
    'Jingle (music)': 'Music',
    'Jingle bell': 'Music',
    'Jingle, tinkle': 'Source-ambiguous sounds',
    'Keyboard (musical)': 'Music',
    'Keys jangling': 'Sounds of things',
    'Knock': 'Sounds of things',
    'Laughter': 'Human sounds',
    'Lawn mower': 'Sounds of things',
    'Light engine (high frequency)': 'Sounds of things',
    'Liquid': 'Sounds of things',
    'Livestock, farm animals, working animals': 'Animal',
    'Lullaby': 'Music',
    'Machine gun': 'Sounds of things',
    'Mains hum': 'Channel, environment and background',
    'Mallet percussion': 'Music',
    'Mandolin': 'Music',
    'Mantra': 'Music',
    'Maraca': 'Music',
    'Marimba, xylophone': 'Music',
    'Mechanical fan': 'Sounds of things',
    'Mechanisms': 'Sounds of things',
    'Medium engine (mid frequency)': 'Sounds of things',
    'Meow': 'Animal',
    'Microwave oven': 'Sounds of things',
    'Middle Eastern music': 'Music',
    'Moo': 'Animal',
    'Mosquito': 'Animal',
    'Motor vehicle (road)': 'Sounds of things',
    'Motorboat, speedboat': 'Sounds of things',
    'Motorcycle': 'Sounds of things',
    'Mouse': 'Animal',
    'Music': 'Music',
    'Music for children': 'Music',
    'Music of Africa': 'Music',
    'Music of Asia': 'Music',
    'Music of Bollywood': 'Music',
    'Music of Latin America': 'Music',
    'Musical instrument': 'Music',
    'Narration, monologue': 'Human sounds',
    'Neigh, whinny': 'Animal',
    'New-age music': 'Music',
    'Noise': 'Channel, environment and background',
    'Ocean': 'Natural sounds',
    'Oink': 'Animal',
    'Opera': 'Music',
    'Orchestra': 'Music',
    'Organ': 'Music',
    'Outside, rural or natural': 'Channel, environment and background',
    'Outside, urban or manmade': 'Channel, environment and background',
    'Owl': 'Animal',
    'Pant': 'Human sounds',
    'Patter': 'Animal',
    'Percussion': 'Music',
    'Piano': 'Music',
    'Pig': 'Animal',
    'Pigeon, dove': 'Animal',
    'Ping': 'Source-ambiguous sounds',
    'Pink noise': 'Channel, environment and background',
    'Pizzicato': 'Music',
    'Plop': 'Source-ambiguous sounds',
    'Plucked string instrument': 'Music',
    'Police car (siren)': 'Sounds of things',
    'Pop music': 'Music',
    'Pour': 'Sounds of things',
    'Power tool': 'Sounds of things',
    'Power windows, electric windows': 'Sounds of things',
    'Printer': 'Sounds of things',
    'Progressive rock': 'Music',
    'Propeller, airscrew': 'Sounds of things',
    'Psychedelic rock': 'Music',
    'Pulleys': 'Sounds of things',
    'Pulse': 'Source-ambiguous sounds',
    'Pump (liquid)': 'Sounds of things',
    'Punk rock': 'Music',
    'Purr': 'Animal',
    'Quack': 'Animal',
    'Race car, auto racing': 'Sounds of things',
    'Radio': 'Channel, environment and background',
    'Rail transport': 'Sounds of things',
    'Railroad car, train wagon': 'Sounds of things',
    'Rain': 'Natural sounds',
    'Rain on surface': 'Natural sounds',
    'Raindrop': 'Natural sounds',
    'Rapping': 'Human sounds',
    'Ratchet, pawl': 'Sounds of things',
    'Rattle': 'Animal',
    'Rattle (instrument)': 'Music',
    'Reggae': 'Music',
    'Reverberation': 'Channel, environment and background',
    'Reversing beeps': 'Sounds of things',
    'Rhythm and blues': 'Music',
    'Rimshot': 'Music',
    'Ringtone': 'Sounds of things',
    'Roar': 'Animal',
    'Roaring cats (lions, tigers)': 'Animal',
    'Rock and roll': 'Music',
    'Rock music': 'Music',
    'Rodents, rats, mice': 'Animal',
    'Roll': 'Source-ambiguous sounds',
    'Rowboat, canoe, kayak': 'Sounds of things',
    'Rub': 'Source-ambiguous sounds',
    'Rumble': 'Source-ambiguous sounds',
    'Run': 'Human sounds',
    'Rustle': 'Source-ambiguous sounds',
    'Rustling leaves': 'Natural sounds',
    'Sad music': 'Music',
    'Sailboat, sailing ship': 'Sounds of things',
    'Salsa music': 'Music',
    'Sampler': 'Music',
    'Sanding': 'Sounds of things',
    'Sawing': 'Sounds of things',
    'Saxophone': 'Music',
    'Scary music': 'Music',
    'Scissors': 'Sounds of things',
    'Scrape': 'Source-ambiguous sounds',
    'Scratch': 'Source-ambiguous sounds',
    'Scratching (performance technique)': 'Music',
    'Screaming': 'Human sounds',
    'Sewing machine': 'Sounds of things',
    'Shatter': 'Sounds of things',
    'Sheep': 'Animal',
    'Ship': 'Sounds of things',
    'Shofar': 'Music',
    'Shout': 'Human sounds',
    'Shuffle': 'Human sounds',
    'Shuffling cards': 'Sounds of things',
    'Sidetone': 'Channel, environment and background',
    'Sigh': 'Human sounds',
    'Silence': 'Source-ambiguous sounds',
    'Sine wave': 'Source-ambiguous sounds',
    'Singing': 'Human sounds',
    'Singing bowl': 'Music',
    'Single-lens reflex camera': 'Sounds of things',
    'Sink (filling or washing)': 'Sounds of things',
    'Siren': 'Sounds of things',
    'Sitar': 'Music',
    'Sizzle': 'Source-ambiguous sounds',
    'Ska': 'Music',
    'Skateboard': 'Sounds of things',
    'Skidding': 'Sounds of things',
    'Slam': 'Sounds of things',
    'Slap, smack': 'Source-ambiguous sounds',
    'Sliding door': 'Sounds of things',
    'Slosh': 'Sounds of things',
    'Smash, crash': 'Source-ambiguous sounds',
    'Smoke detector, smoke alarm': 'Sounds of things',
    'Snake': 'Animal',
    'Snare drum': 'Music',
    'Sneeze': 'Human sounds',
    'Snicker': 'Human sounds',
    'Sniff': 'Human sounds',
    'Snoring': 'Human sounds',
    'Snort': 'Human sounds',
    'Sonar': 'Sounds of things',
    'Song': 'Music',
    'Soul music': 'Music',
    'Sound effect': 'Source-ambiguous sounds',
    'Soundtrack music': 'Music',
    'Speech': 'Human sounds',
    'Speech synthesizer': 'Human sounds',
    'Splash, splatter': 'Sounds of things',
    'Splinter': 'Sounds of things',
    'Spray': 'Sounds of things',
    'Squawk': 'Animal',
    'Squeak': 'Sounds of things',
    'Squeal': 'Source-ambiguous sounds',
    'Squish': 'Sounds of things',
    'Static': 'Channel, environment and background',
    'Steam': 'Natural sounds',
    'Steam whistle': 'Sounds of things',
    'Steel guitar, slide guitar': 'Music',
    'Steelpan': 'Music',
    'Stir': 'Sounds of things',
    'Stomach rumble': 'Human sounds',
    'Stream': 'Natural sounds',
    'String section': 'Music',
    'Strum': 'Music',
    'Subway, metro, underground': 'Sounds of things',
    'Swing music': 'Music',
    'Synthesizer': 'Music',
    'Synthetic singing': 'Human sounds',
    'Tabla': 'Music',
    'Tambourine': 'Music',
    'Tap': 'Sounds of things',
    'Tapping (guitar technique)': 'Music',
    'Tearing': 'Source-ambiguous sounds',
    'Techno': 'Music',
    'Telephone': 'Sounds of things',
    'Telephone bell ringing': 'Sounds of things',
    'Telephone dialing, DTMF': 'Sounds of things',
    'Television': 'Channel, environment and background',
    'Tender music': 'Music',
    'Theme music': 'Music',
    'Theremin': 'Music',
    'Throat clearing': 'Human sounds',
    'Throbbing': 'Channel, environment and background',
    'Thump, thud': 'Sounds of things',
    'Thunder': 'Natural sounds',
    'Thunderstorm': 'Natural sounds',
    'Thunk': 'Sounds of things',
    'Tick': 'Sounds of things',
    'Tick-tock': 'Sounds of things',
    'Timpani': 'Music',
    'Tire squeal': 'Sounds of things',
    'Toilet flush': 'Sounds of things',
    'Tools': 'Sounds of things',
    'Toot': 'Sounds of things',
    'Toothbrush': 'Sounds of things',
    'Traditional music': 'Music',
    'Traffic noise, roadway noise': 'Sounds of things',
    'Train': 'Sounds of things',
    'Train horn': 'Sounds of things',
    'Train wheels squealing': 'Sounds of things',
    'Train whistle': 'Sounds of things',
    'Trance music': 'Music',
    'Trickle, dribble': 'Sounds of things',
    'Trombone': 'Music',
    'Truck': 'Sounds of things',
    'Trumpet': 'Music',
    'Tubular bells': 'Music',
    'Tuning fork': 'Music',
    'Turkey': 'Animal',
    'Typewriter': 'Sounds of things',
    'Typing': 'Sounds of things',
    'Ukulele': 'Music',
    'Vacuum cleaner': 'Sounds of things',
    'Vehicle': 'Sounds of things',
    'Vehicle horn, car horn, honking': 'Sounds of things',
    'Vibraphone': 'Music',
    'Vibration': 'Channel, environment and background',
    'Video game music': 'Music',
    'Violin, fiddle': 'Music',
    'Vocal music': 'Music',
    'Wail, moan': 'Human sounds',
    'Walk, footsteps': 'Human sounds',
    'Water': 'Natural sounds',
    'Water tap, faucet': 'Sounds of things',
    'Waterfall': 'Natural sounds',
    'Waves, surf': 'Natural sounds',
    'Wedding music': 'Music',
    'Whack, thwack': 'Source-ambiguous sounds',
    'Whale vocalization': 'Animal',
    'Wheeze': 'Human sounds',
    'Whimper': 'Human sounds',
    'Whimper (dog)': 'Animal',
    'Whip': 'Source-ambiguous sounds',
    'Whir': 'Source-ambiguous sounds',
    'Whispering': 'Human sounds',
    'Whistle': 'Sounds of things',
    'Whistling': 'Human sounds',
    'White noise': 'Channel, environment and background',
    'Whoop': 'Human sounds',
    'Whoosh, swoosh, swish': 'Sounds of things',
    'Wild animals': 'Animal',
    'Wind': 'Natural sounds',
    'Wind chime': 'Music',
    'Wind instrument, woodwind instrument': 'Music',
    'Wind noise (microphone)': 'Natural sounds',
    'Wood': 'Sounds of things',
    'Wood block': 'Music',
    'Writing': 'Sounds of things',
    'Yell': 'Human sounds',
    'Yip': 'Animal',
    'Yodeling': 'Human sounds',
    'Zing': 'Source-ambiguous sounds',
    'Zipper (clothing)': 'Sounds of things',
    'Zither': 'Music',
}
